module.exports = {
	title: 'device',
	version: 0,
	description: 'Schema for device summary',
	type: 'object',
	properties: {
		deviceCode: { type: 'string', maxLength: 36 },
		deviceName: { type: 'string' },
		deviceIp: { type: 'string', format: 'ipv4' },
		registerIp: { type: 'string', format: 'ipv4' },
		status: { type: 'string' },
		deviceModel: { type: 'string' },
		orgCode: { type: 'string' },
		orgName: { type: 'string' },
		serverCode: { type: 'string' },
		serverName: { type: 'string' },
		deviceCategory: { type: 'string' },
		deviceCategoryName: { type: 'string' },
		deviceType: { type: 'string' },
		deviceTypeName: { type: 'string' },
		domainId: { type: 'string' },
		offlineReasonCode: { type: 'string' },
		offlineReasonDesc: { type: 'string' },
		enableEdit: { type: 'string' },
		enableDelete: { type: 'string' },
		enableWeb: { type: 'string' },
		manufacturer: { type: 'string' },
		manufacturerName: { type: 'string' },
		protocolType: { type: 'string' },
		protocolTypeName: { type: 'string' },
	},
	required: [
		'deviceCode',
		'deviceName',
		'deviceIp',
		'registerIp',
		'status',
		'deviceModel',
		'orgCode',
		'orgName',
		'serverCode',
		'serverName',
		'deviceCategory',
		'deviceCategoryName',
		'deviceType',
		'deviceTypeName',
		'domainId',
	],
	primaryKey: 'deviceCode',
};
