module.exports = {
	title: 'parkinglot',
	version: 0,
	description: 'Schema for parking lot configuration',
	type: 'object',
	properties: {
		id: { type: 'string', maxLength: 36 },
		idleParkingSpaceCount: { type: 'string' },
		exitTimeTemplateId: { type: 'string' },
		enableLastPlaceOneMore: { type: 'string' },
		enableExitAutoPassUnRegisterVehicle: { type: 'string' },
		parkingSpaceStatisticsRules: {
			type: 'array',
			items: { type: 'object' },
		},
		enableParkingSpaceStatistics: { type: 'string' },
		enableExitCheckAuth: { type: 'string' },
		enterRuleType: { type: 'string' },
		enableExitAutoPassUnlicensedVehicle: { type: 'string' },
		enableFirstPlaceOneLess: { type: 'string' },
		enableEmptyParkingSpaceEnterRule: { type: 'string' },
		enableExitCheckAuthByCard: { type: 'string' },
		positions: {
			type: 'array',
			items: {
				type: 'object',
				properties: {
					issueVehicleRules: {
						type: 'array',
						items: { type: 'object' },
					},
					points: {
						type: 'array',
						items: {
							type: 'object',
							properties: {
								pointName: { type: 'string' },
								direction: { type: 'string' },
								coordinateTime: { type: 'string' },
								bindingVtoChannels: {
									type: 'array',
									items: { type: 'object' },
								},
								bindingCommonLedChannels: {
									type: 'array',
									items: { type: 'object' },
								},
								multipleCameras: { type: 'string' },
								remark: { type: 'string' },
								bindingItcChannels: {
									type: 'array',
									items: {
										type: 'object',
										properties: {
											channelType: { type: 'string' },
											channelId: { type: 'string' },
										},
										required: ['channelType', 'channelId'],
									},
								},
							},
							required: [
								'pointName',
								'direction',
								'coordinateTime',
								'bindingItcChannels',
							],
						},
					},
					positionName: { type: 'string' },
					remark: { type: 'string' },
					passRules: {
						type: 'array',
						items: { type: 'object' },
					},
				},
				required: ['positionName', 'points'],
			},
		},
		enableLastPlaceOneLess: { type: 'string' },
		bindingRemainLedChannels: {
			type: 'array',
			items: { type: 'object' },
		},
		issueVehicles: { type: 'string' },
		exitRuleType: { type: 'string' },
		enableEnterAutoPassUnRegisterVehicle: { type: 'string' },
		parkingLotName: { type: 'string' },
		parkingSpaceStatisticsType: { type: 'string' },
		bindingDetectors: {
			type: 'array',
			items: { type: 'object' },
		},
		enableEnterAutoPassBlockVehicle: { type: 'string' },
		enableEnterAutoPassUnlicensedVehicle: { type: 'string' },
		enableFirstPlaceOneMore: { type: 'string' },
		enableExitCardAuth: { type: 'string' },
		totalParkingSpaceCount: { type: 'string' },
		enableEnterCardAuth: { type: 'string' },
		parkingSpaceStatisticsRuleType: { type: 'string' },
		fuzzyMatchBitCount: { type: 'string' },
		enableOverrideEnterRepeatVehicle: { type: 'string' },
		enterTimeTemplateId: { type: 'string' },
		bindingLeds: {
			type: 'array',
			items: { type: 'object' },
		},
		enableExitAutoPassBlockVehicle: { type: 'string' },
		bindingLedPartitions: {
			type: 'array',
			items: { type: 'object' },
		},
		enableEnterCheckAuthByCard: { type: 'string' },
		enableFuzzyMatch: { type: 'string' },
		enableEnterCheckAuth: { type: 'string' },
	},
	required: ['parkingLotName'],
	primaryKey: 'id',
};
