module.exports = {
	title: 'vehicle',
	version: 0,
	description: 'Schema for Vehicle Info',
	type: 'object',
	primaryKey: {
		key: 'id',
		fields: ['id'],
	},
	additionalProperties: true,
	properties: {
		id: { type: 'string', maxLength: 36 },
		entranceStartTime: { type: 'string', pattern: '^\\d+$' },
		entranceEndTime: { type: 'string', pattern: '^\\d+$' },
		surveyStartTime: { type: 'string', pattern: '^\\d+$' },
		surveyEndTime: { type: 'string', pattern: '^\\d+$' },
		plateNo: { type: 'string' },
		vehicleColor: { type: 'string' },
		vehicleBrand: { type: 'string' },
		remark: { type: 'string' },
		entranceLongTerm: { type: 'string', enum: ['0', '1'] },
		surveyLongTerm: { type: 'string', enum: ['0', '1'] },
		entranceRemainingTime: { type: 'string', pattern: '^\\d+$' },
		entranceEffectiveStatus: { type: 'string', enum: ['0', '1'] },
		surveyRemainingTime: { type: 'string', pattern: '^\\d+$' },
		surveyEffectiveStatus: { type: 'string', enum: ['0', '1'] },
		entranceGroups: {
			type: 'object',
			properties: {
				groupId: { type: 'string' },
				groupName: { type: 'string' },
				groupColor: { type: 'string' },
				remark: { type: 'string' },
				level: { type: 'string' },
			},
			required: ['groupId', 'groupName', 'groupColor'],
		},
		surveyGroups: {
			type: 'object',
			properties: {
				groupId: { type: 'string' },
				groupName: { type: 'string' },
				groupColor: { type: 'string' },
				remark: { type: 'string' },
			},
			required: ['groupId', 'groupName', 'groupColor'],
		},
		personInfo: {
			type: 'object',
			properties: {
				personId: { type: 'string' },
				personName: { type: 'string' },
				companyName: { type: 'string' },
				orgCode: { type: 'string' },
				orgName: { type: 'string' },
				facePictures: { type: 'string', format: 'uri' },
				email: { type: 'string', format: 'email' },
				tel: { type: 'string', pattern: '^\\+?[0-9]+$' },
				enableParkingSpace: { type: 'string', enum: ['0', '1'] },
				parkingSpaceNum: { type: 'string', pattern: '^\\d+$' },
				remark: { type: 'string' },
				enableEntranceGroup: { type: 'string', enum: ['0', '1'] },
			},
			required: ['personId', 'personName', 'orgCode'],
		},
		capturePictures: {
			type: 'array',
			items: { type: 'string' },
		},
	},
	required: [
		'id', // only marking id as required; you can add more if necessary
	],
};
